# Generated by Django 4.0.4 on 2022-05-29 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.IntegerField()),
                ('description', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('acceptedDelivery', models.BooleanField(default=False)),
                ('deliveryMan', models.IntegerField()),
            ],
        ),
    ]
