# Generated by Django 4.0.5 on 2022-06-18 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerId', models.IntegerField()),
                ('angelId', models.IntegerField()),
                ('orderId', models.IntegerField()),
                ('estimatedTime', models.TimeField()),
                ('customerConfirmation', models.BooleanField()),
                ('angelConfirmation', models.BooleanField()),
            ],
        ),
    ]
