# Generated by Django 4.0.4 on 2022-06-17 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_createdordershistoryids_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='createdOrdersHistoryIds',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='deliveredOrdersHistoryIds',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
