# Generated by Django 4.0.5 on 2022-06-18 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectId', models.IntegerField()),
                ('subjectId', models.IntegerField()),
                ('deal', models.CharField(choices=[('0', 'DELIVERY'), ('1', 'ORDERING')], max_length=1)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
    ]
